pipelines:
  default:
    - step:
        name: Build with BXARM (Self-hosted)
        runs-on:
          - self.hosted
          - linux
        script:
          - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/ChecksumLibrary.ewp -make Debug -parallel `nproc` -log all
          - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/project.ewp -make Debug -parallel `nproc` -log all
        artifacts:
          - project/EWARM/Debug/Exe/ChecksumLibrary.a
          - project/EWARM/Debug/Exe/project.out    
    - parallel:
      - step:
          name: IAR C-STAT Static Analysis - Library (Self-hosted)
          runs-on:
            - self.hosted
            - linux
          script:  
            - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_analyze Debug -parallel `nproc` -log all
            - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_report Debug -log all 
          artifacts:
            - project/EWARM/Debug/C-STAT/*.html
      - step:
          name: IAR C-STAT Static Analysis - Application (Self-hosted)
          runs-on:
            - self.hosted
            - linux
          script:
            - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/project.ewp -cstat_analyze Debug -parallel `nproc` -log all
            - /opt/iarsystems/bxarm/common/bin/iarbuild project/EWARM/project.ewp -cstat_report Debug -log all
          artifacts:
            - project/EWARM/Debug/C-STAT/*.html