image:
  name: ghcr.io/iarsystems/arm:9.60.4-st

pipelines:
  default:
    - step:
        name: Build
        script:
          - echo "Number of cores:" $(nproc)
          - iarbuild project/EWARM/ChecksumLibrary.ewp -make Debug -parallel `nproc` -log all
          - iarbuild project/EWARM/project.ewp -make Debug -parallel `nproc` -log all
        artifacts:
          - project/EWARM/Debug/Exe/ChecksumLibrary.a
          - project/EWARM/Debug/Exe/project.out    
    - parallel:
      - step:
          name: Library - Static Analysis
          script:  
            - iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_analyze Debug -parallel `nproc` -log all
            - iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_report Debug -log all 
          artifacts:
            - project/EWARM/Debug/C-STAT/*.html
      - step:
          name: Application - Static Analysis
          script:
            - iarbuild project/EWARM/project.ewp -cstat_analyze Debug -parallel `nproc` -log all
            - iarbuild project/EWARM/project.ewp -cstat_report Debug -log all
          artifacts:
            - project/EWARM/Debug/C-STAT/*.html
